apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-details-svc
  labels:
    app: app-details
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-details
  template:
    metadata:
      labels:
        app: app-details
    spec:
      containers:
      - name: c-details-svc
        image: raemondarellano/microsvc-detailservice:latest
        ports:
        - containerPort: 3003 


---

apiVersion: v1
kind: Service
metadata:
  name: service-details-svc
spec:
  selector:
    app: app-details
  type: LoadBalancer
  ports:
    - port: 3003
      targetPort: 3003
#      nodePort: 30012